apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yolo-api-ingress
  namespace: yolo-app
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
    - hosts:
        - api.yolo-app.local
      secretName: yolo-api-tls
  rules:
    - host: api.yolo-app.local
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: yolo-api
                port:
                  number: 8080
