apiVersion: v1
kind: Secret
metadata:
  name: {{ include "yolo-app.fullname" . }}-secret
  labels:
    {{- include "yolo-app.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USER: {{ .Values.database.username | b64enc | quote }}
  DB_PASSWORD: {{ .Values.database.password | b64enc | quote }}
