apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yolo-app-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: yolo-project
  source:
    repoURL: 'https://github.com/MelvinjoseC/YOLO-app.git'
    targetRevision: HEAD
    path: deploy/helm/yolo-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: yolo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
