apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: yolo-project
  namespace: argocd
spec:
  description: "ArgoCD Project for the YOLO Cloud-Native Application Suite"
  sourceRepos:
    - "https://github.com/MelvinjoseC/YOLO-app.git"
  destinations:
    - namespace: yolo-app
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
